name: GuBu CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['GuBu CI']
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Ubuntu
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PEMKEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Load nvm and node environment
            export NVM_DIR="/home/ubuntu/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            sudo cd /home/8Jo/gubu_batch

            sudo git switch main

            sudo git pull

            sudo echo "${{ secrets.SERVER_ENV }}" > .env

            sudo npm ci

            sudo npm run build

            sudo pm2 delete gubu || true

            sudo pm2 start dist/main.js --name gubu

            sudo pm2 save

            sudo pm2 startup