name: GuBu-Batch CI

on:
  workflow_dispatch:
  push:
    branches: [dev, main]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [dev, main]

jobs:
  ci-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Archive build
        run: tar -czf gubu-batch.tar.gz dist/

      - name: Decode SSH key
        run: echo "${{ secrets.SERVER_PEMKEY }}" > /tmp/private_key.pem
        shell: bash

      - name: Set permissions for the SSH key
        run: chmod 600 /tmp/private_key.pem
        shell: bash

      - name: Copy build to deployment server
        run: |
          scp -i /tmp/private_key.pem -o StrictHostKeyChecking=no -P ${{ secrets.SERVER_SSH }} gubu-batch.tar.gz ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/ubuntu/8JO/gubu_batch/
        shell: bash
      #주석